version: '3.8'

services:
  backend:
    build:
      context: ./backend/tama_backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/tama_backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_dist:/app/dist
    environment:
      - NODE_ENV=${ENVIRONMENT}
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - internal

  db:
    build:
      context: ./backend
      dockerfile: Dockerfile.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal

  redis:
    image: redis:alpine
    networks:
      - internal

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - frontend_dist:/usr/share/nginx/html
    networks:
      - internal
    depends_on:
      - frontend
    entrypoint: /wait-for-build.sh
    command: [ "nginx", "-g", "daemon off;" ]

networks:
  internal:

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_dist:

